---
- name: Create OpenShift VMs
  hosts: localhost
  gather_facts: true
  vars:
    vm_dns_domain: "{{ ocp_master_vm_dns_domain }}"
    is_stateless: False
    node_role: ""
  vars_files:
  - default_vars.yaml
  tasks:
  - name: Login to RHV
    ovirt_auth:
      insecure: true

  - name: fact for ips
    set_fact:
      master_ip_addresses: "{{ ocp_master_ips.split(',') }}"
      worker_ip_addresses: "{{ ocp_worker_ips.split(',') }}"
      bootstrap_ip_addresses: "{{ ocp_bootstrap_ip.split(',') }}"

  - name: create bootstrap vm
    import_tasks: create_ovirt_vms.yaml
    vars:
      vm_name_prefix: "{{ bootstrap_vm_name_prefix }}"
      vm_index: "{{ bootstrap_vm_name_index }}"
      number_of_vms: 1
      cpus: "{{ ocp_master_vm_cpus }}"
      memory: "{{ ocp_master_vm_memory }}"
      ip_addresses: "{{ bootstrap_ip_addresses }}"
      node_role: bootstrap

  - name: create master vms
    import_tasks: create_ovirt_vms.yaml 
    vars:
      vm_name_prefix: "{{ master_vm_name_prefix }}"
      vm_index: "{{ master_vm_name_index }}"
      number_of_vms: "{{ ocp_master_vm_count }}"
      cpus: "{{ ocp_master_vm_cpus }}"
      memory: "{{ ocp_master_vm_memory }}"
      ip_addresses: "{{ master_ip_addresses }}"
      node_role: master

  - name: create worker vms
    import_tasks: create_ovirt_vms.yaml
    vars:
      vm_name_prefix: "{{ worker_vm_name_prefix }}"
      vm_index: "{{ worker_vm_name_index }}"
      number_of_vms: "{{ ocp_worker_vm_count }}"
      cpus: "{{ ocp_worker_vm_cpus }}"
      memory: "{{ ocp_worker_vm_memory }}"
      ip_addresses: "{{ worker_ip_addresses }}"
      node_role: worker
 
